import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { type PortalStatus, formatAppointmentDate, statusCopy } from "@/lib/portal";
import { CalendarClock, CalendarDays, Check, CheckCircle2, ChevronDown, ClipboardCheck, FileText, Filter, Grid2X2, MessageSquare, RefreshCw, RotateCcw, Search, TriangleAlert, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";
import AppointmentDateHistoryDialog from "../components/AppointmentDateHistoryDialog";
import AppointmentChatDialog from "../components/AppointmentChatDialog";
import AppointmentDetailsDialog, { type AppointmentDetail } from "../components/AppointmentDetailsDialog";
import LoadingTruck from "../components/LoadingTruck";
import UnscheduledReceiptDialog from "../components/UnscheduledReceiptDialog";
import PortalLayout from "./PortalLayout";

type Appointment = AppointmentDetail;
type StatusTab = "all" | PortalStatus;

const tabs: { id: StatusTab; label: string; icon: typeof Grid2X2 }[] = [
  { id: "all", label: "Todos", icon: Grid2X2 }, { id: "pending", label: "Pendente", icon: RotateCcw }, { id: "scheduled", label: "Agendado", icon: CalendarDays }, { id: "received", label: "Recebido", icon: ClipboardCheck }, { id: "completed", label: "Concluído", icon: CheckCircle2 }, { id: "backlog", label: "Backlog", icon: TriangleAlert }, { id: "rejected", label: "Rejeitado", icon: X },
];
const statusStyle: Record<PortalStatus, string> = { pending: "bg-rvd-blue-pale text-rvd-plum", scheduled: "bg-rvd-plum-pale text-rvd-plum", received: "bg-rvd-lilac-blue text-rvd-plum", completed: "bg-rvd-blue text-rvd-plum", backlog: "bg-rvd-plum-pale text-rvd-plum", rejected: "bg-rvd-lilac-blue text-rvd-plum" };

function todayValue() { return new Date().toLocaleDateString("en-CA"); }
function datePart(value: Date | string) { return new Date(value).toLocaleDateString("en-CA"); }

export default function OperatorDashboard() {
  const [location, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const auth = trpc.auth.me.useQuery();
  const [activeStatus, setActiveStatus] = useState<StatusTab>("all");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [date, setDate] = useState("");
  const [invoiceNumber, setInvoiceNumber] = useState("");
  const [supplierName, setSupplierName] = useState("");
  const [recipientCnpj, setRecipientCnpj] = useState("");
  const [selected, setSelected] = useState<Appointment | null>(null);
  const [details, setDetails] = useState<Appointment | null>(null);
  const [dateHistory, setDateHistory] = useState<Appointment | null>(null);
  const [preNoteTarget, setPreNoteTarget] = useState<Appointment | null>(null);
  const [chatTarget, setChatTarget] = useState<Appointment | null>(null);
  const [receiptOpen, setReceiptOpen] = useState(() => new URLSearchParams(window.location.search).get("modal") === "receipt");
  const [scheduleDate, setScheduleDate] = useState(todayValue());
  const [scheduleTime, setScheduleTime] = useState("09:00");
  const logout = trpc.auth.logout.useMutation({ onSuccess: () => setLocation("/") });
  const listInput = useMemo(() => ({ date: date || undefined, status: activeStatus === "all" ? undefined : activeStatus, invoiceNumber: invoiceNumber || undefined, supplierName: supplierName || undefined, recipientCnpj: recipientCnpj || undefined }), [activeStatus, date, invoiceNumber, recipientCnpj, supplierName]);
  const agenda = trpc.appointments.list.useQuery(listInput);
  const allAgenda = trpc.appointments.list.useQuery();
  const activeSupplier = trpc.appointments.activeForSupplier.useQuery({ supplierId: selected?.supplierId ?? 1 }, { enabled: Boolean(selected) });
  const updateStatus = trpc.appointments.updateStatus.useMutation({ onSuccess: () => { toast.success("Status atualizado."); utils.appointments.list.invalidate(); utils.calendar.list.invalidate(); }, onError: error => toast.error(error.message) });
  const rescue = trpc.appointments.rescue.useMutation({ onSuccess: () => { toast.success("Item resgatado para novo tratamento."); utils.appointments.list.invalidate(); }, onError: error => toast.error(error.message) });
  const schedule = trpc.appointments.schedule.useMutation({ onSuccess: () => { toast.success("Agendamento confirmado."); setSelected(null); utils.appointments.list.invalidate(); utils.calendar.list.invalidate(); }, onError: error => toast.error(error.message) });
  const confirmPreNote = trpc.appointments.confirmPreNote.useMutation({ onSuccess: () => { toast.success("Pré-nota confirmada com sucesso."); setPreNoteTarget(null); utils.appointments.list.invalidate(); }, onError: error => toast.error(error.message) });

  useEffect(() => { if (auth.data?.role === "supplier") setLocation("/fornecedor"); if (auth.data === null) setLocation("/"); }, [auth.data, setLocation]);
  useEffect(() => {
    const requestedId = Number(new URLSearchParams(window.location.search).get("chat"));
    if (!requestedId) return;
    const appointment = allAgenda.data?.find(item => item.id === requestedId);
    if (appointment) setChatTarget(appointment);
  }, [allAgenda.data, location]);
  const counters = useMemo(() => ({ all: allAgenda.data?.length ?? 0, pending: allAgenda.data?.filter(item => item.status === "pending").length ?? 0, scheduled: allAgenda.data?.filter(item => item.status === "scheduled").length ?? 0, received: allAgenda.data?.filter(item => item.status === "received").length ?? 0, completed: allAgenda.data?.filter(item => item.status === "completed").length ?? 0, backlog: allAgenda.data?.filter(item => item.status === "backlog").length ?? 0, rejected: allAgenda.data?.filter(item => item.status === "rejected").length ?? 0 }), [allAgenda.data]);
  if (auth.isLoading) return <LoadingTruck label="Preparando a central do operador" />;
  if (!auth.data || auth.data.role === "supplier") return <div className="min-h-screen bg-white" />;

  const clearFilters = () => { setDate(""); setInvoiceNumber(""); setSupplierName(""); setRecipientCnpj(""); setActiveStatus("all"); };
  const openSchedule = (item: Appointment) => { setSelected(item); const dateTime = new Date(item.scheduledFor); setScheduleDate(datePart(dateTime)); setScheduleTime(dateTime.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit", hour12: false })); };
  const confirmSchedule = () => { if (!selected || !scheduleDate || !scheduleTime) return toast.error("Informe a data e a hora do recebimento."); schedule.mutate({ appointmentId: selected.id, scheduledFor: new Date(`${scheduleDate}T${scheduleTime}:00`).toISOString() }); };

  return <PortalLayout user={auth.data} title="Agendamentos" subtitle="Gestão e monitoramento de agendamentos e recebimentos." onLogout={() => logout.mutate()}>
    <section className="rounded-3xl bg-[#fafbfc] p-4 sm:p-6">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><p className="font-display text-2xl font-extrabold text-rvd-plum">Agendamentos</p><p className="mt-1 text-sm text-rvd-plum">Gestão e monitoramento de agendamentos e recebimentos.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => { setDate(todayValue()); setActiveStatus("all"); }} variant="ghost" className="rounded-xl border border-rvd-plum-soft bg-white font-bold text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum"><CalendarDays className="size-4" />Agendamentos do Dia</Button><Button onClick={() => setReceiptOpen(true)} variant="default" style={{ backgroundColor: "#782078", color: "#ffffff" }} className="rounded-xl !bg-[#782078] font-bold !text-white shadow-sm hover:!bg-[#641a64] focus-visible:ring-2 focus-visible:ring-rvd-plum"><ClipboardCheck className="size-4" />Recebimento sem Agendamento</Button><Button onClick={() => setActiveStatus("backlog")} variant="ghost" className="rounded-xl border border-rvd-plum-soft bg-white font-bold text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum"><RefreshCw className="size-4" />Backlog</Button><Button onClick={() => setFiltersOpen(value => !value)} className="rounded-xl bg-rvd-plum font-bold text-white hover:bg-rvd-plum"><Filter className="size-4" />Filtros<ChevronDown className={`size-4 transition ${filtersOpen ? "rotate-180" : ""}`} /></Button></div></div>
      {filtersOpen && <div className="mt-6 rounded-3xl border border-rvd-plum-soft bg-white p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FilterField label="Número da nota" value={invoiceNumber} onChange={setInvoiceNumber} placeholder="NF-e..." /><FilterField label="Nome do fornecedor" value={supplierName} onChange={setSupplierName} placeholder="Parte do nome..." /><FilterField label="CNPJ destinatário" value={recipientCnpj} onChange={setRecipientCnpj} placeholder="00.000.000/0000-00" /><div><Label className="text-xs font-bold uppercase tracking-wide text-rvd-plum">Data inicial</Label><Input type="date" value={date} onChange={event => setDate(event.target.value)} className="mt-2 border-rvd-plum-soft text-rvd-plum" /></div></div><Button onClick={clearFilters} variant="ghost" className="mt-5 px-0 text-rvd-plum hover:bg-transparent hover:text-rvd-plum"><X className="size-4" />Limpar filtros</Button></div>}
      <div className="mt-7 flex flex-wrap justify-center gap-2">{tabs.map(tab => { const Icon = tab.icon; const count = counters[tab.id]; const active = activeStatus === tab.id; const showsCounter = tab.id === "pending" || tab.id === "scheduled"; return <button key={tab.id} onClick={() => setActiveStatus(tab.id)} className={`relative inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold uppercase tracking-wide transition ${active ? "border-rvd-plum bg-rvd-plum text-white" : "border-rvd-plum-soft bg-white text-rvd-plum hover:bg-rvd-plum-pale"}`}><Icon className="size-3.5" />{tab.label}{showsCounter && count > 0 && <span className={`-right-2 -top-2 absolute flex size-5 items-center justify-center rounded-full text-[10px] font-extrabold ${active ? "bg-rvd-blue text-rvd-plum" : "bg-rvd-plum text-white"}`}>{count}</span>}</button>; })}</div>
    </section>
    <section className="mt-6 overflow-hidden rounded-3xl border border-rvd-plum-soft bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-left"><thead className="bg-[#fafbfc]"><tr className="text-[11px] font-bold uppercase tracking-[0.1em] text-rvd-plum"><th className="px-6 py-5">Status</th><th className="px-6 py-5">Fornecedor</th><th className="px-6 py-5">Destinatário</th><th className="px-6 py-5">Nota fiscal</th><th className="px-6 py-5">Pedido</th><th className="px-6 py-5">{activeStatus === "rejected" ? "Motivo da recusa" : "Data agendamento"}</th><th className="px-6 py-5">Ícones de ação</th><th className="px-6 py-5 text-right">Ação</th></tr></thead><tbody>{agenda.isLoading ? <tr><td colSpan={8} className="py-20 text-center text-sm font-bold text-rvd-plum">Carregando agendamentos...</td></tr> : agenda.data?.length ? agenda.data.map(item => <AppointmentRow key={item.id} item={item} activeStatus={activeStatus} onDetails={() => setDetails(item)} onHistory={() => setDateHistory(item)} onChat={() => setChatTarget(item)} onPreNote={() => item.preNoteConfirmedAt ? toast.info("Pré-nota já confirmada.") : setPreNoteTarget(item)} onSchedule={() => openSchedule(item)} onUpdate={(status, reason) => updateStatus.mutate({ appointmentId: item.id, status, rejectionReason: reason })} onRescue={() => rescue.mutate({ appointmentId: item.id })} />) : <tr><td colSpan={8} className="px-6 py-16 text-center"><Search className="mx-auto size-7 text-rvd-plum" /><p className="mt-3 font-bold text-rvd-plum">Nenhum agendamento encontrado</p><p className="mt-1 text-sm text-rvd-plum">Ajuste os filtros ou selecione outra aba de status.</p></td></tr>}</tbody></table></div></section>
    <ScheduleDialog item={selected} open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} date={scheduleDate} time={scheduleTime} onDate={setScheduleDate} onTime={setScheduleTime} onConfirm={confirmSchedule} loading={schedule.isPending} activeAppointments={activeSupplier.data?.filter(item => item.id !== selected?.id) ?? []} />
    <AppointmentDetailsDialog appointment={details} open={Boolean(details)} onOpenChange={open => !open && setDetails(null)} onHistory={() => { if (details) { setDateHistory(details); setDetails(null); } }} />
    <AppointmentDateHistoryDialog appointment={dateHistory} open={Boolean(dateHistory)} onOpenChange={open => !open && setDateHistory(null)} />
    <AppointmentChatDialog appointment={chatTarget} currentUserId={auth.data.id} open={Boolean(chatTarget)} onOpenChange={open => { if (!open) { setChatTarget(null); if (window.location.search.includes("chat=")) setLocation("/operador"); } }} />
    <PreNoteConfirmDialog item={preNoteTarget} open={Boolean(preNoteTarget)} onOpenChange={open => !open && setPreNoteTarget(null)} onConfirm={() => preNoteTarget && confirmPreNote.mutate({ appointmentId: preNoteTarget.id })} loading={confirmPreNote.isPending} />
    <UnscheduledReceiptDialog open={receiptOpen} onOpenChange={setReceiptOpen} onRegistered={() => { utils.appointments.list.invalidate(); utils.calendar.list.invalidate(); }} />
  </PortalLayout>;
}

function FilterField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <div><Label className="text-xs font-bold uppercase tracking-wide text-rvd-plum">{label}</Label><div className="relative mt-2"><Search className="absolute left-3 top-3 size-4 text-rvd-plum" /><Input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="border-rvd-plum-soft pl-9 text-rvd-plum placeholder:text-rvd-plum/60" /></div></div>; }

function AppointmentRow({ item, activeStatus, onDetails, onHistory, onChat, onPreNote, onSchedule, onUpdate, onRescue }: { item: Appointment; activeStatus: StatusTab; onDetails: () => void; onHistory: () => void; onChat: () => void; onPreNote: () => void; onSchedule: () => void; onUpdate: (status: Exclude<PortalStatus, "pending">, reason?: string) => void; onRescue: () => void }) { const displaySupplier = item.invoiceSupplierName || item.supplierName || "Fornecedor"; return <tr className="border-t border-rvd-plum-soft align-middle"><td className="px-6 py-5"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold uppercase tracking-wide ${statusStyle[item.status as PortalStatus]}`}>{statusCopy[item.status as PortalStatus]}</span></td><td className="px-6 py-5"><p className="max-w-40 font-bold leading-5 text-rvd-plum">{displaySupplier}</p><p className="mt-1 text-xs text-rvd-plum">{item.supplierEmail}</p></td><td className="px-6 py-5"><p className="font-bold text-rvd-plum">{item.recipientCnpj || "—"}</p><p className="mt-1 text-xs text-rvd-plum">Destinatário</p></td><td className="px-6 py-5"><p className="font-display text-lg font-extrabold text-rvd-plum">{item.invoiceNumber || "—"}</p><p className="text-xs text-rvd-plum">{item.source === "manual_xml" ? "XML" : "Portal"}</p></td><td className="px-6 py-5"><span className="rounded bg-rvd-plum-pale px-2 py-1 text-xs font-bold text-rvd-plum">{item.purchaseOrder || "—"}</span></td><td className="px-6 py-5">{activeStatus === "rejected" ? <p className="max-w-36 text-sm font-semibold leading-5 text-red-700">{item.rejectionReason || "Motivo não informado"}</p> : <><p className="font-bold text-rvd-plum">{new Date(item.scheduledFor).toLocaleDateString("pt-BR")}</p><p className="text-sm text-rvd-plum">{new Date(item.scheduledFor).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</p></>}</td><td className="px-6 py-5"><div className="flex items-center gap-3 text-rvd-plum"><ActionIcon label="Abrir detalhes da nota" icon={FileText} onClick={onDetails} /><ActionIcon label="Histórico de datas" icon={CalendarClock} onClick={onHistory} />{item.status === "scheduled" && <ActionIcon label="Reagendar" icon={CalendarDays} onClick={onSchedule} />}<ActionIcon label="Conversar sobre esta nota" icon={MessageSquare} onClick={onChat} /><ActionIcon label={item.preNoteConfirmedAt ? "Pré-nota confirmada" : "Confirmar pré-nota"} icon={ClipboardCheck} onClick={onPreNote} confirmed={Boolean(item.preNoteConfirmedAt)} /></div></td><td className="px-6 py-5 text-right"><PrimaryAction status={item.status as PortalStatus} onSchedule={onSchedule} onUpdate={onUpdate} onRescue={onRescue} /></td></tr>; }
function ActionIcon({ label, icon: Icon, onClick, confirmed = false }: { label: string; icon: typeof FileText; onClick: () => void; confirmed?: boolean }) { return <button onClick={onClick} title={label} className={`rounded-lg p-1.5 hover:bg-rvd-plum-pale ${confirmed ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-100" : ""}`}><Icon className="size-4" /></button>; }
function PrimaryAction({ status, onSchedule, onUpdate, onRescue }: { status: PortalStatus; onSchedule: () => void; onUpdate: (status: Exclude<PortalStatus, "pending">, reason?: string) => void; onRescue: () => void }) { const buttonClass = "h-9 rounded-xl px-4 text-xs font-bold"; if (status === "pending" || status === "backlog") return <Button onClick={onSchedule} className={`${buttonClass} bg-rvd-plum text-white hover:bg-rvd-plum`}>Agendar</Button>; if (status === "scheduled") return <div className="flex justify-end gap-2"><Button onClick={onSchedule} variant="ghost" className={`${buttonClass} border border-rvd-plum-soft text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum`}>Reagendar</Button><Button onClick={() => onUpdate("received")} className={`${buttonClass} bg-rvd-plum text-white hover:bg-rvd-plum`}>Recebido</Button><Button onClick={() => onUpdate("rejected", "Recusado pelo operador")} variant="ghost" className={`${buttonClass} border border-rvd-plum-soft text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum`}>Rejeitar</Button></div>; if (status === "received") return <Button onClick={() => onUpdate("completed")} className={`${buttonClass} bg-rvd-plum text-white hover:bg-rvd-plum`}>Concluir</Button>; if (status === "rejected") return <Button onClick={onRescue} className={`${buttonClass} bg-rvd-blue text-rvd-plum hover:bg-rvd-blue-pale`}><RefreshCw className="size-3.5" />Resgatar</Button>; return <span className="text-xs font-bold text-rvd-plum">Consulta</span>; }

function ScheduleDialog({ item, open, onOpenChange, date, time, onDate, onTime, onConfirm, loading, activeAppointments }: { item: Appointment | null; open: boolean; onOpenChange: (open: boolean) => void; date: string; time: string; onDate: (value: string) => void; onTime: (value: string) => void; onConfirm: () => void; loading: boolean; activeAppointments: { id: number; serviceType: string; scheduledFor: Date; status: string }[] }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl border-0 bg-transparent p-0 shadow-none"><div className="grid gap-4 md:grid-cols-2"><section className="rounded-[2rem] bg-white p-7 shadow-2xl"><DialogHeader><DialogTitle className="font-display text-2xl font-extrabold text-rvd-plum">Agendar recebimento</DialogTitle><DialogDescription className="text-rvd-plum">Defina a data e hora para o fornecedor.</DialogDescription></DialogHeader><div className="mt-7 space-y-5"><div><Label className="font-bold text-rvd-plum">Data</Label><Input type="date" value={date} onChange={event => onDate(event.target.value)} className="mt-2 h-12 border-rvd-plum-soft text-rvd-plum" /></div><div><Label className="font-bold text-rvd-plum">Hora</Label><Input type="time" value={time} onChange={event => onTime(event.target.value)} className="mt-2 h-12 border-rvd-plum-soft text-rvd-plum" /></div><div className="flex justify-end gap-3 pt-4"><Button variant="ghost" onClick={() => onOpenChange(false)} className="font-bold text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum">Cancelar</Button><Button onClick={onConfirm} disabled={loading} className="h-12 rounded-xl bg-rvd-plum px-5 font-bold text-white hover:bg-rvd-plum">{loading ? "Confirmando..." : "Confirmar agendamento"}</Button></div></div></section><aside className="rounded-[2rem] bg-white p-7 shadow-2xl"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-rvd-plum" /><div><h3 className="font-display text-lg font-extrabold text-rvd-plum">Agendamentos deste fornecedor</h3><p className="text-xs text-rvd-plum">Agrupe novas entregas nas janelas já reservadas quando possível.</p></div></div>{activeAppointments.length ? <div className="mt-6 space-y-3">{activeAppointments.map(active => <article key={active.id} className="rounded-2xl bg-rvd-plum-pale p-4"><p className="font-bold text-rvd-plum">{active.serviceType}</p><p className="mt-1 text-sm text-rvd-plum">{formatAppointmentDate(active.scheduledFor)}</p></article>)}</div> : <div className="mt-16 text-center"><CalendarDays className="mx-auto size-9 text-rvd-blue" /><p className="mt-4 font-bold text-rvd-plum">Nenhum agendamento ativo</p><p className="mt-1 text-sm text-rvd-plum">Este fornecedor não tem outras notas agendadas no momento.</p></div>}</aside></div></DialogContent></Dialog>; }
function PreNoteConfirmDialog({ item, open, onOpenChange, onConfirm, loading }: { item: Appointment | null; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-md overflow-hidden rounded-[2rem] !border !border-rvd-plum-soft !bg-white p-0 shadow-2xl"><div className="bg-white p-7"><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700"><ClipboardCheck className="size-5" /></span><div><DialogTitle className="font-display text-xl font-extrabold text-rvd-plum">Confirmar pré-nota</DialogTitle><DialogDescription className="mt-1 text-rvd-plum">Nota {item?.invoiceNumber || "não identificada"}</DialogDescription></div></div><p className="mt-6 text-sm font-medium text-rvd-plum">A pré-nota foi realizada no sistema?</p><div className="mt-7 flex gap-3"><Button variant="ghost" onClick={() => onOpenChange(false)} className="h-11 flex-1 rounded-xl border border-rvd-plum-soft bg-white font-bold text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum">Cancelar</Button><Button onClick={onConfirm} disabled={loading} className="h-11 flex-1 rounded-xl bg-emerald-600 font-bold text-white hover:bg-emerald-700">{loading ? "Confirmando..." : "Confirmar"}</Button></div></div></DialogContent></Dialog>; }
