import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { filterReportAppointments, formatReportDate, getReportInvoiceValueRangeError, toConsolidatedReportRows, type ReportFilters } from "@/lib/reports";
import { trpc } from "@/lib/trpc";
import { Banknote, CalendarRange, ClipboardList, Download, FileSpreadsheet, Filter, RefreshCw, Search, TableProperties, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { useLocation } from "wouter";
import PortalLayout from "./PortalLayout";

const initialFilters: ReportFilters = { status: "all" };
const statusOptions = [
  ["all", "Todos"], ["pending", "Pendente"], ["scheduled", "Agendado"], ["received", "Recebido"], ["completed", "Concluído"], ["rejected", "Rejeitado"],
] as const;

export default function ReportsPage() {
  const [, setLocation] = useLocation();
  const auth = trpc.auth.me.useQuery();
  const appointments = trpc.appointments.list.useQuery();
  const logout = trpc.auth.logout.useMutation({ onSuccess: () => setLocation("/") });
  const [filters, setFilters] = useState<ReportFilters>(initialFilters);
  const [view, setView] = useState<"consolidated" | "detailed">("consolidated");
  useEffect(() => { if (auth.data?.role === "supplier") setLocation("/fornecedor"); if (auth.data === null) setLocation("/"); }, [auth.data, setLocation]);
  const filtered = useMemo(() => filterReportAppointments(appointments.data ?? [], filters), [appointments.data, filters]);
  const rows = useMemo(() => toConsolidatedReportRows(filtered), [filtered]);
  const invoiceValueError = useMemo(() => getReportInvoiceValueRangeError(filters.invoiceValueMin, filters.invoiceValueMax), [filters.invoiceValueMin, filters.invoiceValueMax]);
  const setFilter = <K extends keyof ReportFilters>(key: K, value: ReportFilters[K]) => setFilters(current => ({ ...current, [key]: value }));
  const exportExcel = () => {
    const worksheet = XLSX.utils.json_to_sheet(rows);
    worksheet["!cols"] = [{ wch: 14 }, { wch: 30 }, { wch: 20 }, { wch: 16 }, { wch: 14 }, { wch: 23 }, { wch: 23 }, { wch: 32 }];
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Consolidado");
    XLSX.writeFile(workbook, `relatorio-consolidado-rvd-${new Date().toISOString().slice(0, 10)}.xlsx`);
  };
  if (!auth.data || auth.data.role === "supplier") return <div className="min-h-screen bg-white" />;

  return <PortalLayout user={auth.data} title="Relatórios" subtitle="Histórico completo das notas lançadas." onLogout={() => logout.mutate()}>
    <section className="overflow-hidden rounded-3xl bg-[#172136] p-6 text-white shadow-xl shadow-rvd-plum/10 sm:p-8"><div className="flex flex-col gap-6 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-4"><span className="flex size-14 items-center justify-center rounded-2xl bg-white/10 text-rvd-blue"><ClipboardList className="size-7" /></span><div><p className="font-display text-3xl font-extrabold">Relatórios</p><p className="mt-1 text-sm text-white/75">Consolidado operacional de agendamentos e recebimentos.</p></div></div><div className="flex flex-wrap gap-3"><Button onClick={() => appointments.refetch()} variant="ghost" className="h-11 rounded-xl bg-white font-bold text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum"><RefreshCw className="size-4" />Carregar relatório</Button><Button onClick={exportExcel} disabled={!rows.length || Boolean(invoiceValueError)} className="h-11 rounded-xl bg-rvd-blue font-bold text-rvd-plum hover:bg-rvd-blue-pale"><Download className="size-4" />Exportar Excel ({rows.length})</Button></div></div></section>

    <section className="mt-7"><div className="flex flex-wrap items-center gap-2"><button onClick={() => setView("consolidated")} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-extrabold transition ${view === "consolidated" ? "bg-rvd-plum text-white shadow-sm" : "bg-rvd-plum-pale text-rvd-plum hover:bg-rvd-plum-soft"}`}><TableProperties className="size-4" />Consolidado</button><button onClick={() => setView("detailed")} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-extrabold transition ${view === "detailed" ? "bg-rvd-plum text-white shadow-sm" : "bg-rvd-plum-pale text-rvd-plum hover:bg-rvd-plum-soft"}`}><FileSpreadsheet className="size-4" />Detalhado</button><span className="ml-1 text-sm text-rvd-plum">{view === "consolidated" ? "Uma linha por nota — visão geral." : "Consulta com todos os dados operacionais disponíveis."}</span></div></section>

    <section className="mt-7 rounded-3xl bg-[#fafbfc] p-5 sm:p-7"><div className="flex items-center gap-2"><Filter className="size-5 text-rvd-plum" /><p className="text-sm font-bold uppercase tracking-[0.14em] text-rvd-plum">Filtros</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FilterDate label="Agendamento: início" value={filters.scheduledStart || ""} onChange={value => setFilter("scheduledStart", value)} /><FilterDate label="Agendamento: fim" value={filters.scheduledEnd || ""} onChange={value => setFilter("scheduledEnd", value)} /><FilterSelect label="Status" value={filters.status || "all"} onChange={value => setFilter("status", value as ReportFilters["status"])} options={statusOptions} /><FilterText label="Fornecedor (nome ou CNPJ)" value={filters.supplier || ""} onChange={value => setFilter("supplier", value)} placeholder="Buscar fornecedor..." /><FilterText label="CNPJ destinatário" value={filters.recipientCnpj || ""} onChange={value => setFilter("recipientCnpj", value)} placeholder="00.000.000/0000-00" /><FilterCurrency label="Valor mínimo da NF" value={filters.invoiceValueMin || ""} onChange={value => setFilter("invoiceValueMin", value)} /><FilterCurrency label="Valor máximo da NF" value={filters.invoiceValueMax || ""} onChange={value => setFilter("invoiceValueMax", value)} /><div className="flex items-end"><Button onClick={() => setFilters(initialFilters)} variant="ghost" className="h-11 text-rvd-plum hover:bg-rvd-plum-pale hover:text-rvd-plum">Limpar filtros</Button></div></div>{invoiceValueError ? <p className="mt-3 text-sm font-semibold text-red-700" role="alert">{invoiceValueError}</p> : <p className="mt-3 text-xs text-rvd-plum/75">Informe os valores em reais, por exemplo: R$ 1.000,00.</p>}</section>

    <section className="mt-7 overflow-hidden rounded-3xl border border-rvd-plum-soft bg-white"><div className="flex flex-col gap-3 border-b border-rvd-plum-soft px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-rvd-plum">Consolidado</p><h2 className="mt-1 font-display text-xl font-extrabold text-rvd-plum">Notas e recebimentos</h2></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-rvd-plum-pale px-3 py-1.5 text-xs font-bold text-rvd-plum"><Truck className="size-3.5" />{rows.length} notas encontradas</span></div>{appointments.isLoading ? <div className="py-16 text-center font-bold text-rvd-plum">Carregando consolidado...</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1220px] text-left"><thead className="bg-[#fafbfc]"><tr className="text-[10px] font-bold uppercase tracking-[0.12em] text-rvd-plum"><th className="px-5 py-4">Nota fiscal</th><th className="px-5 py-4">Fornecedor</th><th className="px-5 py-4">CNPJ destinatário</th><th className="px-5 py-4">Pedido</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Data agendamento</th><th className="px-5 py-4">Data recebida</th><th className="px-5 py-4">Item recebido</th></tr></thead><tbody>{filtered.length ? filtered.map(item => <tr key={item.id} className="border-t border-rvd-plum-soft text-sm text-rvd-plum"><td className="px-5 py-4 font-display text-base font-extrabold">{item.invoiceNumber || "—"}</td><td className="px-5 py-4 font-bold">{item.invoiceSupplierName || item.supplierName || "—"}</td><td className="px-5 py-4">{item.recipientCnpj || "—"}</td><td className="px-5 py-4">{item.purchaseOrder || "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-rvd-plum-pale px-2.5 py-1 text-xs font-bold">{item.status === "pending" ? "Pendente" : item.status === "scheduled" ? "Agendado" : item.status === "received" ? "Recebido" : item.status === "completed" ? "Concluído" : "Rejeitado"}</span></td><td className="px-5 py-4 font-semibold">{formatReportDate(item.scheduledFor)}</td><td className="px-5 py-4 font-semibold">{formatReportDate(item.receivedAt)}</td><td className="px-5 py-4">{item.status === "received" || item.status === "completed" ? item.serviceType : "Aguardando recebimento"}</td></tr>) : <tr><td colSpan={8} className="px-5 py-16 text-center"><Search className="mx-auto size-6 text-rvd-plum" /><p className="mt-3 font-bold text-rvd-plum">Nenhuma nota encontrada</p><p className="mt-1 text-sm text-rvd-plum">Ajuste os filtros para consultar o consolidado.</p></td></tr>}</tbody></table></div>}</section>
  </PortalLayout>;
}

function FilterDate({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><Label className="text-[10px] font-bold uppercase tracking-wide text-rvd-plum">{label}</Label><div className="relative mt-2"><CalendarRange className="pointer-events-none absolute left-3 top-3 size-4 text-rvd-plum" /><Input type="date" value={value} onChange={event => onChange(event.target.value)} className="h-11 border-rvd-plum-soft bg-white pl-10 text-rvd-plum" /></div></div>; }
function FilterText({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <div><Label className="text-[10px] font-bold uppercase tracking-wide text-rvd-plum">{label}</Label><div className="relative mt-2"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-rvd-plum" /><Input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-11 border-rvd-plum-soft bg-white pl-10 text-rvd-plum placeholder:text-rvd-plum/60" /></div></div>; }
function FilterCurrency({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><Label className="text-[10px] font-bold uppercase tracking-wide text-rvd-plum">{label}</Label><div className="relative mt-2"><Banknote className="pointer-events-none absolute left-3 top-3 size-4 text-rvd-plum" /><Input inputMode="decimal" value={value} onChange={event => onChange(event.target.value)} placeholder="R$ 0,00" className="h-11 border-rvd-plum-soft bg-white pl-10 text-rvd-plum placeholder:text-rvd-plum/60" /></div></div>; }
function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) { return <div><Label className="text-[10px] font-bold uppercase tracking-wide text-rvd-plum">{label}</Label><select value={value} onChange={event => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-rvd-plum-soft bg-white px-3 text-sm font-semibold text-rvd-plum focus:outline-none focus:ring-2 focus:ring-rvd-blue">{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></div>; }
